# Project Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=2.1.0
maven_group=net.supersonic
archives_base_name=supersonic-client

# Environment Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.7

# Fabric API
fabric_version=0.92.0+1.20.1
